In [1]:
#1. kutuphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#2. Veri Onisleme
#2.1. Veri Yukleme
veriler = pd.read_csv('odev_tenis.txt')
#pd.read_csv("veriler.csv")
veriler

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [3]:
from sklearn import preprocessing
veriler2 = veriler.apply(preprocessing.LabelEncoder().fit_transform)

c = veriler2.iloc[:,:1]
c

outlook
0         2
1         2
2         0
3         1
4         1
5         1
6         0
7         2
8         2
9         1
10        2
11        0
12        0
13        1

In [4]:
from sklearn import preprocessing
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
print(c)

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [5]:
havaDurumu = pd.DataFrame(data=c,index = range(14),columns=["o","r","s"])
sonVeriler = pd.concat([havaDurumu,veriler.iloc[:,1:3]],axis=1)
sonVeriler = pd.concat([sonVeriler,veriler2.iloc[:,-2:]],axis=1)
sonVeriler

o    r    s  temperature  humidity  windy  play
0   0.0  0.0  1.0           85        85      0     0
1   0.0  0.0  1.0           80        90      1     0
2   1.0  0.0  0.0           83        86      0     1
3   0.0  1.0  0.0           70        96      0     1
4   0.0  1.0  0.0           68        80      0     1
5   0.0  1.0  0.0           65        70      1     0
6   1.0  0.0  0.0           64        65      1     1
7   0.0  0.0  1.0           72        95      0     0
8   0.0  0.0  1.0           69        70      0     1
9   0.0  1.0  0.0           75        80      0     1
10  0.0  0.0  1.0           75        70      1     1
11  1.0  0.0  0.0           72        90      1     1
12  1.0  0.0  0.0           81        75      0     1
13  0.0  1.0  0.0           71        91      1     0

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(sonVeriler.iloc[:,:-1],sonVeriler.iloc[:,:-1],test_size=0.33,random_state=0)

In [7]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)


In [8]:
import statsmodels.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int) , values = sonVeriler.iloc[:,:-1],axis=1)
X_l = sonVeriler.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(sonVeriler.iloc[:,-1:],X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                   play   R-squared:                       0.483
Model:                            OLS   Adj. R-squared:                  0.160
Method:                 Least Squares   F-statistic:                     1.493
Date:                Sun, 16 Apr 2023   Prob (F-statistic):              0.292
Time:                        01:08:34   Log-Likelihood:                -4.9501
No. Observations:                  14   AIC:                             21.90
Df Residuals:                       8   BIC:                             25.73
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             3.4007      1.859      1.829      0.1

C:\Users\d_ali\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [9]:
sonVeriler = sonVeriler.iloc[:,1:]


In [12]:
import statsmodels.api as sm


X = np.append(arr = np.ones((14,1)).astype(int), values=sonVeriler.iloc[:,:-1], axis=1 )
X_l = sonVeriler.iloc[:,[0,1,2,3,4]].values
r_ols = sm.OLS(endog = sonVeriler.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)




                                 OLS Regression Results                                
Dep. Variable:                   play   R-squared (uncentered):                   0.738
Model:                            OLS   Adj. R-squared (uncentered):              0.593
Method:                 Least Squares   F-statistic:                              5.071
Date:                Sun, 16 Apr 2023   Prob (F-statistic):                      0.0174
Time:                        01:09:48   Log-Likelihood:                         -7.3955
No. Observations:                  14   AIC:                                      24.79
Df Residuals:                       9   BIC:                                      27.99
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

C:\Users\d_ali\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1736: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "
